all:main main_search_all main2
main:main.cpp
	g++ -std=c++11 main.cpp -o main
main2:main2.cpp
	g++ -std=c++11 main2.cpp -o main2
main_search_all:main_search_all.cpp
	g++ -std=c++11 main_search_all.cpp -o main_search_all
clean:
	rm main main_search_all main2
