all:main gen trans main_n2
main:main.cpp
	g++ -std=c++11 main.cpp -o main
main_n2:main_n2.cpp
	g++ -std=c++11 main_n2.cpp -o main_n2
gen:gen.cpp
	g++ -std=c++11 gen.cpp -o gen
trans:trans.cpp
	g++ -std=c++11 trans.cpp -o trans
clean:
	rm main main_n2
